---

plugins:
  - babel

env:
  node: true

parser: babel-eslint

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  "arrow-body-style": ["error", "always"]
  "allowTernary": true
  "object-curly-newline": ["error", "never"]

